version: 2.1
orbs:
    android: circleci/android@0.2.0
jobs:
    build:
        executor: android/android
        steps:
            - checkout
            - run:
                  name: Run build
                  command: ./gradlew build  -x test
    test:
        executor: android/android
        steps:
            - checkout
            - run:
                  name: Run tests
                  command: ./gradlew test
#                  I do not know purpose of crashing tests because local they are successful
#                  command: ./gradlew test -x testDebugUnitTest -x testReleaseUnitTest
# Orchestrate or schedule a set of jobs
workflows:
    # Name of the workflow
    build_and_test:
        jobs:
            - build
            - test:
                  requires:
                      - build
      
