version: 2.1
orbs:
  android: circleci/android@0.2.0
jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - run:
          command: ./gradlew build  -x test
  test:
    executor: android/android
    steps:
      - checkout
      - run:
          command: ./gradlew test -x testDebugUnitTest testReleaseUnitTest

# Orchestrate or schedule a set of jobs
workflows:
  # Name of the workflow
  build_and_test:
    jobs:
      - build
      - test:
           requires:
            - build
      
