version: 2.1
orbs:
  android: circleci/android@0.2.0
jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - run:
          command: ./gradlew build
  test:
    executor: android/android
    steps:
      - checkout
      - run:
          command: ./gradlew test

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  build:
    # Run the welcome/run job in its own container
    jobs:
      - build
      - test
      
